### PR TITLE
update to latest sbt 0.13.x

### PR DESCRIPTION
**Pull request by larsrh**
First part of #173

### CODE REVIEW

**Comment by larsrh** [comment]
@tpolecat This one should be (mostly) source compatible, unless plugin users rely on internals. Hence, I filed this against master.

**Comment by tpolecat** [comment]
Sorry, I was busy with family stuff yesterday. Looks great.

**Comment by larsrh** [comment]
Going forward, I propose the following plan:

* drop 2.10 support
* drop 0.13.x support
* file a PR with these two to the `series/0.6` branch

Is that fine with you?

**Comment by tpolecat** [comment]
Yep, sounds great! 👍

**Comment by larsrh** [comment]
@tpolecat Continued in #175.

**Pull request merged**
