### PR TITLE
simplify build

### PR DESCRIPTION
**Pull request by larsrh**
* merges `tests` and `plugin` projects (they have similar configuration)
* `+ publishLocal` should do the right thing, so no need for an alias
* `scripted` should also do the right thing

This should hopefully make future development simpler.

### CODE REVIEW

**Comment by larsrh** [comment]
```
[error] java.lang.IllegalStateException: Ivy file not found in cache for org.tpolecat#tut_2.12;0.6.1-SNAPSHOT!
[error] 	at sbt.internal.librarymanagement.ResolutionCache.getResolvedModuleDescriptor(ResolutionCache.scala:66)
```

Clear the cache, maybe? Can't reproduce this locally.

**Comment by tpolecat** [comment]
How does `+publishLocal` know not to build the plugin for 2.11 and 2.13?

**Comment by larsrh** [comment]
sbt-doge is now a built-in feature of sbt 1.0. You'll notice when running `++2.11.11`.

As for the failure on Travis, no idea what's going on. The IllegalStateException looks like a bug to me.

**Comment by tpolecat** [comment]
Hm, don't know. I need to run but I'll do some digging later. Thanks again for your help!

**Pull request closed without merging**
