### PR TITLE
Fix #65: assure incomplete input doesn't pass compilation

### LINKED ISSUE #65: Incomplete code in tut sheds doesn't fail
Discovered in version 0.4.0.

If a tut shed ends when a normal REPL would prompt for more input, tut doesn't complain that the code is incomplete.

example input (I'm using apostophes because I can't figure out how to escape backticks in GitHub markdown):

```
'''tut
{
'''
```

what I see in output:

```
scala>   {
```

I seem to forget closing braces and hit this often :)

_Edit_: I had been using `tut:silent` a lot and forgot that `tut` includes the `scala>` prompt in the output, so I wrote an irrelevant detail.

### PR DESCRIPTION
**Pull request by felixmulder**
This PR is against the correct branch, removes the O(n^2) complexity from the helper, adds a test

Let me know if you have some reservations about this implementation @tpolecat - I just want to be able to close #65 :)

### CODE REVIEW

**Comment by tpolecat** [comment]
Cool, thanks for this! I'm at NEScala but will try to have a look on the flight back.

**Comment by felixmulder** [comment]
Roooooooob, let's make tut safe again 🇺🇸 🎉 🍾

**Comment by tpolecat** [comment]
Hi, thanks for the reminder. Looks great!

**Comment by tpolecat** [comment]
0.6.4 is out, by the way, with this change.

**Comment by felixmulder** [comment]
Amazing! Prematurely opened a PR against sbt-microsites 😹

**Pull request merged**
