### PR TITLE
Implements `passthrough`

### PR DESCRIPTION
**Pull request by metasim**
Per #172

Signed-off-by: Simeon H.K. fitch <fitch@astraea.io>

### CODE REVIEW

**Comment by metasim** [comment]
@tpolecat Any thoughts on this? Adjustments? Not interested?

**Comment by tpolecat** [comment]
Hi, sorry, lots of PRs in the queue. I'll get to it.

**Comment by olafurpg** [comment]
This would be a very nice feature! We are in the process of porting the scalafix docs to sbt-microsite  (WIP https://olafurpg.github.io/scalafix). If I understand this PR correctly, we could use `passthrough` to automatically render bullet lists like in https://olafurpg.github.io/scalafix/docs/users/rules to link all scalafix rules from one page.

**Comment by metasim** [comment]
@tpolecat Is this a no-go? Or just still flooded with PRs?

**Comment by tpolecat** [comment]
Sorry, trying to dig myself out. Trying to get a release out soon.

**Comment by tpolecat** [comment]
A complication is that all these things need to be ported to the 0.6 branch.

**Comment by metasim** [comment]
Anything I can do to help with the 0.6 branch? Separate pull request?

**Pull request merged**
