### PR TITLE
Scala 2.12.0-RC2

### PR DESCRIPTION
**Pull request by larsrh**
... and a release, please :wink:

### CODE REVIEW

**Comment by tpolecat** [comment]
👍 Thanks!

**Comment by larsrh** [comment]
@tpolecat Somewhat relatedly; is there any reason why the Travis build is not split up into multiple jobs? That would make things so much faster.

**Comment by tpolecat** [comment]
@larsrh only because I don't know how to do it. Be my guest!

**Comment by larsrh** [comment]
OK, I'm noting it for the weekend :smile: But this PR can go ahead without it.

**Pull request merged**
