### PR TITLE
Migrate to SBT AutoPlugin

### PR DESCRIPTION
**Pull request by guersam**
It's based upon #93, being a separate PR because it breaks the API.

### CODE REVIEW

**Comment by tpolecat** [comment]
This looks great but I'm going to sit on it for 0.5 ... there will be a 0.4.2 release first. Thanks! :+1:

**Comment by guersam** [comment]
Fine, then I'll look for further API improvement, which may introduce more
aggressive changes :)

**Comment by metasim** [comment]
+1 for this.

**Comment by tpolecat** [comment]
Closing via #150

**Pull request closed without merging**
